
services:
  - docker

script:
  - docker-compose build --no-cache
  - docker-compose up -d
  - docker-compose down

  - docker-compose -f docker-compose-mqtt.yml up -d
  - docker-compose -f docker-compose-mqtt.yml down
